In [ ]:
# ! pip install -q openai datasets pandas tqdm dotenv

### Imports

In [1]:
from datasets import load_dataset
from openai import OpenAI
import os
import json
import mlflow
import pandas as pd
from utils import generate_urls, calculate_invoice_accuracies, key_level_metrics
from prompt import register_prompt
from model import log_invoice_extraction_model

from dotenv import load_dotenv
from mlflow.models import make_metric


load_dotenv()

d:\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

True

### Config

In [2]:
MLFLOW_TRACKING_URI = "http://localhost:8080/"
MODEL_NAME = "gpt-5-nano"
REASONING = "high"
MLFLOW_EXPERIMENT_NAME = "cord-v2-gpt5-baseline"
PROMPT_NAME = f"invoice-extraction-prompt"
PROMPT_VERSION = "1"

### Initialize MLflow and OpenAI environment

In [3]:
client = OpenAI()
os.environ["MLFLOW_TRACKING_URI"] = MLFLOW_TRACKING_URI
os.environ["MLFLOW_EXPERIMENT_NAME"] = MLFLOW_EXPERIMENT_NAME
mlflow.openai.autolog()

### Register prompt and model

In [4]:
register_prompt(prompt_name=PROMPT_NAME)

You are a Vision Language Model designed to extract structured data from invoice receipts.
    Task:
    Convert the invoice receipt into a well-formed JSON object strictly following the schema provided.

    Requirements:
    1. Identify and extract only these sections (if present): `menu`, `sub_menu`, `sub_total`, `total`.
    2. Preserve exact formatting for all the extracted values.
    3. Do not output fields that lack data—omit empty keys.
    4. Do not add any information not present in the invoice.
    5. In case of prices and currencies, ensure to maintain the original format without any modifications.

    Schema:
    {schema}

    Output:
    Return valid, minimal JSON matching this schema - no extraneous keys or null values.

2025/08/16 17:41:57 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for prompt version to finish creation. Prompt name: invoice-extraction-prompt, version 3

In [5]:
model_uri = log_invoice_extraction_model(model_name=MODEL_NAME, reasoning=REASONING, prompt_name=PROMPT_NAME, prompt_version=PROMPT_VERSION)

🏃 View run gpt-5-nano-high at: http://localhost:8080/#/experiments/417204914699444791/runs/ab0a8903186a4041a00b0fad98e36cc3
🧪 View experiment at: http://localhost:8080/#/experiments/417204914699444791

### Load the dataset

In [6]:
dataset = load_dataset("naver-clova-ix/cord-v2")
dataset

DatasetDict({
    train: Dataset({
        features: ['image', 'ground_truth'],
        num_rows: 800
    })
    validation: Dataset({
        features: ['image', 'ground_truth'],
        num_rows: 100
    })
    test: Dataset({
        features: ['image', 'ground_truth'],
        num_rows: 100
    })
})

### Data Preparation

In [7]:
with open("schema.json", "r") as f:
    schema_dict = json.load(f)

schema_dict

{'menu': {'nm': 'name of the menu',
  'num': 'identification number of menu',
  'unitprice': 'unit price of menu',
  'cnt': 'quantity of menu',
  'discountprice': 'discounted price of menu',
  'price': 'total price of menu',
  'itemsubtotal': 'price of each menu after discount applied',
  'vatyn': 'whether the price includes tax or not',
  'etc': 'others',
  'sub': {'nm': 'name of submenu',
   'unitprice': 'unit price of submenu',
   'cnt': 'quantity of submenu',
   'price': 'total price of submenu',
   'etc': 'others'}},
 'sub_total': {'price': 'subtotal price',
  'discount_price': 'discounted price in total',
  'service_price': 'service charge',
  'othersvc_price': 'added charge other than service charge',
  'tax_price': 'tax amount',
  'etc': 'others'},
 'total': {'total_price': 'total price',
  'etc': 'others',
  'cashprice': 'amount of price paid in cash',
  'changeprice': 'amount of change in cash',
  'creditcardprice': 'amount of price paid in credit/debit card',
  'emoneyprice': 'amount of price paid in emoney, point',
  'menutype_cnt': 'total count of type of menu',
  'menuqty_cnt': 'total count of quantity'}}

In [8]:
test_dataset = dataset["test"]

url_list, ground_truth_list = generate_urls(dataset=test_dataset)

schema_dict_list = [schema_dict] * len(url_list)

eval_df = pd.DataFrame(
    {
        "schema": schema_dict_list,
        "image_base64": url_list,
    }
)

eval_df

100%|██████████| 100/100 [00:03<00:00, 27.03it/s]

,schema,image_base64
0,"{'menu': {'nm': 'name of the menu', 'num': 'id...",/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBw...
1,"{'menu': {'nm': 'name of the menu', 'num': 'id...",/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBw...
2,"{'menu': {'nm': 'name of the menu', 'num': 'id...",/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBw...
3,"{'menu': {'nm': 'name of the menu', 'num': 'id...",/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBw...
4,"{'menu': {'nm': 'name of the menu', 'num': 'id...",/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBw...
...,...,...
95,"{'menu': {'nm': 'name of the menu', 'num': 'id...",/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBw...
96,"{'menu': {'nm': 'name of the menu', 'num': 'id...",/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBw...
97,"{'menu': {'nm': 'name of the menu', 'num': 'id...",/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBw...
98,"{'menu': {'nm': 'name of the menu', 'num': 'id...",/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBw...
99,"{'menu': {'nm': 'name of the menu', 'num': 'id...",/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBw...

### Inference and Evaluation

In [9]:
if not os.path.exists("artifacts"):
    os.makedirs("artifacts")
    
eval_with_gt_df = pd.concat([pd.DataFrame({"ground_truth": ground_truth_list}), eval_df], axis=1)
eval_with_gt_df

,ground_truth,schema,image_base64
0,"{'menu': {'nm': '-TICKET CP', 'num': '901016',...","{'menu': {'nm': 'name of the menu', 'num': 'id...",/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBw...
1,"{'menu': [{'nm': 'J.STB PROMO', 'price': '1750...","{'menu': {'nm': 'name of the menu', 'num': 'id...",/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBw...
2,"{'menu': {'nm': 'JASMINE MT ( L )', 'cnt': '1'...","{'menu': {'nm': 'name of the menu', 'num': 'id...",/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBw...
3,"{'menu': {'nm': 'DONAT GULA', 'unitprice': '@1...","{'menu': {'nm': 'name of the menu', 'num': 'id...",/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBw...
4,"{'menu': [{'nm': 'ICE BLACKCOFFE', 'cnt': '2',...","{'menu': {'nm': 'name of the menu', 'num': 'id...",/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBw...
...,...,...,...
95,"{'menu': [{'nm': 'BASO TAHU', 'unitprice': '43...","{'menu': {'nm': 'name of the menu', 'num': 'id...",/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBw...
96,"{'menu': {'nm': 'BBQ Chicken', 'cnt': '1', 'pr...","{'menu': {'nm': 'name of the menu', 'num': 'id...",/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBw...
97,"{'menu': [{'nm': 'BUBUR GO', 'unitprice': '20....","{'menu': {'nm': 'name of the menu', 'num': 'id...",/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBw...
98,"{'menu': [{'nm': 'BLACK PAPPER MEATBALL PAS', ...","{'menu': {'nm': 'name of the menu', 'num': 'id...",/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBw...
99,"{'menu': {'nm': 'FL-Xmas 30 Off', 'cnt': '1', ...","{'menu': {'nm': 'name of the menu', 'num': 'id...",/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBw...

In [10]:
def accuracy_metric(predictions, targets):
    predictions_list = [json.loads(pred) for pred in predictions]
    targets_list = targets.tolist()
    invoice_metrics_df = calculate_invoice_accuracies(targets_list, predictions_list)
    print(invoice_metrics_df)
    key_level_metrics_df = key_level_metrics(targets_list, predictions_list)
    accuracy_value = invoice_metrics_df["accuracy"].mean()
    print("Average accuracy:", accuracy_value)

    return accuracy_value

accuracy_metric = make_metric(
    eval_fn=accuracy_metric, greater_is_better=True, name="avg_accuracy"
)

In [11]:
results = mlflow.evaluate(
    model_uri,
    eval_with_gt_df,
    targets="ground_truth",  # specify which column corresponds to the expected output
    extra_metrics=[
        accuracy_metric,
    ],
)

Downloading artifacts:   0%|          | 0/5 [00:00<?, ?it/s]

2025/08/16 17:42:20 INFO mlflow.tracking.fluent: Active model is set to the logged model with ID: m-ee6244e96459479384d463c9460e42f2
2025/08/16 17:42:20 INFO mlflow.tracking.fluent: Use `mlflow.set_active_model` to set the active model to a different one if needed.
2025/08/16 17:42:23 INFO mlflow.tracking.fluent: Active model is set to the logged model with ID: m-ee6244e96459479384d463c9460e42f2
2025/08/16 17:42:23 INFO mlflow.tracking.fluent: Use `mlflow.set_active_model` to set the active model to a different one if needed.
2025/08/16 17:42:23 INFO mlflow.models.evaluation.utils.trace: Auto tracing is temporarily enabled during the model evaluation for computing some metrics and debugging. To disable tracing, call `mlflow.autolog(disable=True)`.
2025/08/16 17:42:23 INFO mlflow.models.evaluation.evaluators.default: Computing model predictions.
2025/08/16 17:46:13 INFO mlflow.models.evaluation.default_evaluator: Testing metrics on first row...

   invoice_no  total_keys  matched_keys  accuracy
0           0          11             7  0.636364
False negative for key 'sub_total.subtotal_price': GT='60.000', Pred=None
False positive for key 'total.menutype_cnt': GT=None, Pred='1'
False positive for key 'menu.itemsubtotal': GT='60.000', Pred='60,000'
False positive for key 'menu.unitprice': GT=None, Pred='60.000'
False positive for key 'menu.nm': GT='-TICKET CP', Pred='TICKET CP'
False positive for key 'sub_total.price': GT=None, Pred='60.000'
False positive for key 'total.menuqty_cnt': GT='2.00', Pred='2'
Average accuracy: 0.6363636363636364
    invoice_no  total_keys  matched_keys  accuracy
0            0          11             7  0.636364
1            1           8             2  0.250000
2            2          10             3  0.300000
3            3           8             5  0.625000
4            4          14             2  0.142857
..         ...         ...           ...       ...
95          95          13             9  0.692308
96          96          11             6  0.545455
97          97          13             2  0.153846
98          98          13             3  0.230769
99          99          32             8  0.250000

[100 rows x 4 columns]
False negative for key 'sub_total.subtotal_price': GT='60.000', Pred=None
False positive for key 'total.menutype_cnt': GT=None, Pred='1'
False positive for key 'menu.itemsubtotal': GT='60.000', Pred='60,000'
False positive for key 'menu.unitprice': GT=None, Pred='60.000'
False positive for key 'menu.nm': GT='-TICKET CP', Pred='TICKET CP'
False positive for key 'sub_total.price': GT=None, Pred='60.000'
False positive for key 'total.menuqty_cnt': GT='2.00', Pred='2'
False positive for key 'sub_total.price': GT=None, Pred='91000'
False negative for key 'menu.1.price': GT='46000', Pred=None
False negative for key 'menu.1.nm': GT='Y.B.BAT', Pred=None
False negative for key 'menu.2.nm': GT='Y.BASO PROM', Pred=None
False negative for key 'menu.0.nm': GT='J.STB PROMO', Pred=None
False negative for key 'menu.0.price': GT='17500', Pred=None
False negative for key 'menu.2.price': GT='27500', Pred=None
False negative for key 'menu.cnt': GT='1', Pred=None
False negative for key 'menu.sub.nm': GT='COCONUT JELLY ( L )', Pred=None
False positive for key 'sub_total.price': GT=None, Pred='28.000'
False negative for key 'total.menuqty_cnt': GT='1', Pred=None
False negative for key 'sub_total.subtotal_price': GT='28.000', Pred=None
False negative for key 'menu.sub.price': GT='4.000', Pred=None
False negative for key 'menu.price': GT='24.000', Pred=None
False negative for key 'menu.nm': GT='JASMINE MT ( L )', Pred=None
False positive for key 'menu.cnt': GT='1X', Pred='1'
False positive for key 'sub_total.price': GT=None, Pred='11.000'
False positive for key 'total.menuqty_cnt': GT='1.00xITEMs', Pred='1'
False negative for key 'sub_total.subtotal_price': GT='11.000', Pred=None
False positive for key 'total.menutype_cnt': GT=None, Pred='1'
False negative for key 'total.cashprice': GT='200.000', Pred=None
False negative for key 'menu.0.cnt': GT='2', Pred=None
False positive for key 'sub_total.price': GT=None, Pred='194.000'
False negative for key 'sub_total.subtotal_price': GT='194.000', Pred=None
False negative for key 'menu.1.price': GT='61.000', Pred=None
False negative for key 'menu.1.nm': GT='AVOCADO COFFEE', Pred=None
False negative for key 'total.changeprice': GT='25.400', Pred=None
False negative for key 'menu.1.cnt': GT='1', Pred=None
False negative for key 'menu.0.nm': GT='ICE BLACKCOFFE', Pred=None
False negative for key 'menu.0.price': GT='82.000', Pred=None
False negative for key 'menu.2.nm': GT='CHIKEN KATSU FF', Pred=None
False negative for key 'menu.2.price': GT='51.000', Pred=None
False negative for key 'menu.2.cnt': GT='1', Pred=None
False positive for key 'menu.cnt': GT=None, Pred='1'
False negative for key 'sub_total.subtotal_price': GT='28.182', Pred=None
False positive for key 'total.menutype_cnt': GT=None, Pred='1'
False positive for key 'menu.unitprice': GT=None, Pred='28.182'
False positive for key 'sub_total.price': GT=None, Pred='28.182'
False positive for key 'total.menuqty_cnt': GT='1.00', Pred='1'
False positive for key 'menu.1.nm': GT='CHOCO CUS ARD PASTRY', Pred='CHOCO CUS'ARD PASTRY'
False positive for key 'menu.1.unitprice': GT=None, Pred='24.000'
False positive for key 'total.menutype_cnt': GT=None, Pred='3'
False positive for key 'menu.1.num': GT=None, Pred='2'
False positive for key 'menu.2.num': GT=None, Pred='1'
False positive for key 'sub_total.price': GT=None, Pred='46.000'
False positive for key 'menu.0.unitprice': GT=None, Pred='13.000'
False positive for key 'menu.0.num': GT=None, Pred='1'
False positive for key 'menu.1.cnt': GT='2', Pred='1'
False positive for key 'menu.2.unitprice': GT=None, Pred='9.000'
False positive for key 'menu.2.itemsubtotal': GT=None, Pred='9,000'
False positive for key 'menu.1.itemsubtotal': GT=None, Pred='24,000'
False positive for key 'total.menuqty_cnt': GT=None, Pred='3'
False positive for key 'menu.0.nm': GT='EGG TART', Pred='GG TART'
False positive for key 'menu.0.itemsubtotal': GT=None, Pred='13,000'
False positive for key 'total.cashprice': GT='Rp. 111.000', Pred='Rp.111.000'
False negative for key 'menu.sub.nm': GT='ADD CHICKEN BOX', Pred=None
False positive for key 'sub_total.price': GT=None, Pred='100.909'
False positive for key 'total.menuqty_cnt': GT=None, Pred='1'
False negative for key 'sub_total.subtotal_price': GT='100.909', Pred=None
False positive for key 'total.menutype_cnt': GT=None, Pred='1'
False positive for key 'menu.itemsubtotal': GT=None, Pred='100,000'
False negative for key 'menu.sub.price': GT='909', Pred=None
False positive for key 'menu.unitprice': GT=None, Pred='100.000'
False positive for key 'menu.nm': GT='Kupon 15', Pred='ADD CHICKEN BOX'
False negative for key 'menu.sub.1.cnt': GT='1', Pred=None
False negative for key 'menu.sub.0.nm': GT='COOKIE DOH SAUCES', Pred=None
False positive for key 'menu.1.price': GT=None, Pred='0'
False positive for key 'sub_total.othersvc_price': GT=None, Pred='0'
False positive for key 'menu.1.nm': GT=None, Pred='COOKIE DOH SAUCES'
False positive for key 'menu.1.unitprice': GT=None, Pred='0'
False positive for key 'total.menutype_cnt': GT=None, Pred='3'
False positive for key 'sub_total.price': GT=None, Pred='45.455'
False positive for key 'menu.0.unitprice': GT=None, Pred='45.455'
False negative for key 'menu.sub.1.nm': GT='NATA DE COCO', Pred=None
False positive for key 'total.emoneyprice': GT=None, Pred='0'
False negative for key 'menu.cnt': GT='1', Pred=None
False negative for key 'menu.price': GT='45.455', Pred=None
False negative for key 'sub_total.etc': GT='0', Pred=None
False negative for key 'sub_total.subtotal_price': GT='45.455', Pred=None
False negative for key 'menu.sub.1.price': GT='0', Pred=None
False positive for key 'menu.1.cnt': GT=None, Pred='1'
False positive for key 'sub_total.discount_price': GT=None, Pred='0'
False negative for key 'menu.sub.0.price': GT='0', Pred=None
False negative for key 'menu.sub.0.cnt': GT='1', Pred=None
False positive for key 'menu.2.unitprice': GT=None, Pred='0'
False negative for key 'menu.nm': GT='[REG] BLACK SAKURA', Pred=None
False positive for key 'menu.2.cnt': GT=None, Pred='1'
False positive for key 'menu.2.itemsubtotal': GT=None, Pred='0'
False positive for key 'menu.1.itemsubtotal': GT=None, Pred='0'
False positive for key 'sub_total.service_price': GT=None, Pred='0'
False positive for key 'total.cashprice': GT=None, Pred='0'
False positive for key 'menu.0.cnt': GT=None, Pred='1'
False positive for key 'total.menuqty_cnt': GT=None, Pred='3'
False positive for key 'total.changeprice': GT=None, Pred='0'
False positive for key 'menu.2.nm': GT=None, Pred='NATA DE COCO'
False positive for key 'menu.0.nm': GT=None, Pred='[REG] BLACK SAKURA'
False positive for key 'menu.0.price': GT=None, Pred='45.455'
False positive for key 'menu.0.itemsubtotal': GT=None, Pred='45,455'
False positive for key 'menu.2.price': GT=None, Pred='0'
False positive for key 'menu.cnt': GT=None, Pred='1'
False positive for key 'sub_total.price': GT=None, Pred='36000'
False negative for key 'sub_total.subtotal_price': GT='36000', Pred=None
False positive for key 'total.total_price': GT=None, Pred='36000'
False positive for key 'menu.itemsubtotal': GT=None, Pred='36000'
False positive for key 'menu.nm': GT='Bumbu Kaldu Ayam 1', Pred='Bumbu Kaldu Ayam'
False positive for key 'menu.cnt': GT='1 x', Pred='1'
False negative for key 'sub_total.subtotal_price': GT='17.000', Pred=None
False positive for key 'total.menutype_cnt': GT=None, Pred='1'
False positive for key 'menu.itemsubtotal': GT=None, Pred='17,000'
False positive for key 'sub_total.price': GT=None, Pred='17.000'
False positive for key 'total.menuqty_cnt': GT=None, Pred='1'
False positive for key 'sub_total.price': GT=None, Pred='230.000'
False positive for key 'total.menuqty_cnt': GT=None, Pred='1'
False positive for key 'total.menutype_cnt': GT=None, Pred='1'
False positive for key 'menu.cnt': GT=None, Pred='1'
False positive for key 'menu.price': GT=None, Pred='120.000'
False negative for key 'menu.0.num': GT='0571-1854', Pred=None
False negative for key 'menu.1.nm': GT='SHOPPING BAG', Pred=None
False negative for key 'menu.1.unitprice': GT='@880', Pred=None
False positive for key 'total.menutype_cnt': GT=None, Pred='2'
False negative for key 'menu.1.cnt': GT='1', Pred=None
False positive for key 'menu.num': GT=None, Pred='0571-1854'
False positive for key 'menu.itemsubtotal': GT=None, Pred='120,000'
False negative for key 'menu.1.num': GT='1002-0060', Pred=None
False positive for key 'menu.discountprice': GT=None, Pred='120.000'
False positive for key 'menu.unitprice': GT=None, Pred='120.000'
False positive for key 'menu.nm': GT=None, Pred='BLIS WANITA'
False negative for key 'menu.1.itemsubtotal': GT='0', Pred=None
False negative for key 'menu.0.cnt': GT='1', Pred=None
False negative for key 'menu.1.discountprice': GT='100%', Pred=None
False positive for key 'sub_total.price': GT=None, Pred='120.000'
False negative for key 'menu.0.unitprice': GT='@120.000', Pred=None
False positive for key 'total.menuqty_cnt': GT='(2', Pred='2'
False negative for key 'menu.0.nm': GT='BLUS WANITA', Pred=None
False negative for key 'menu.0.itemsubtotal': GT='120,000', Pred=None
False negative for key 'menu.0.discountprice': GT='0%', Pred=None
False positive for key 'menu.cnt': GT=None, Pred='1'
False negative for key 'sub_total.subtotal_price.1': GT='46.636', Pred=None
False negative for key 'sub_total.subtotal_price.0': GT='46.636', Pred=None
False negative for key 'menu.1.price': GT='3.000', Pred=None
False negative for key 'menu.1.nm': GT='A.MINERAL GELAS', Pred=None
False negative for key 'menu.1.unitprice': GT='3.000', Pred=None
False positive for key 'menu.vatyn': GT=None, Pred='No'
False negative for key 'menu.1.cnt': GT='1', Pred=None
False positive for key 'total.menutype_cnt': GT=None, Pred='2'
False positive for key 'menu.sub.cnt': GT=None, Pred='1'
False positive for key 'menu.unitprice': GT=None, Pred='43.63'
False positive for key 'menu.nm': GT=None, Pred='BASO KUAH'
False positive for key 'total.cashprice': GT='52.000', Pred='52.00'
False positive for key 'menu.sub.nm': GT=None, Pred='AA MINERAL GLAS'
False negative for key 'menu.0.cnt': GT='1', Pred=None
False positive for key 'sub_total.price': GT=None, Pred='46.63'
False negative for key 'menu.0.unitprice': GT='43.636', Pred=None
False positive for key 'total.menuqty_cnt': GT=None, Pred='2'
False positive for key 'sub_total.tax_price': GT='4.664', Pred='4.66'
False positive for key 'total.total_price': GT='51.300', Pred='51.30'
False positive for key 'total.changeprice': GT='700', Pred='0.70'
False positive for key 'menu.sub.unitprice': GT=None, Pred='3.00'
False negative for key 'menu.0.nm': GT='BASO KUAH', Pred=None
False negative for key 'menu.0.price': GT='43.636', Pred=None
False positive for key 'menu.sub.price': GT=None, Pred='3.00'
False positive for key 'menu.price': GT=None, Pred='43.63'
False positive for key 'menu.1.unitprice': GT=None, Pred='55.000'
False positive for key 'total.menutype_cnt': GT=None, Pred='6'
False positive for key 'menu.4.itemsubtotal': GT=None, Pred='25,000'
False positive for key 'sub_total.price': GT=None, Pred='238.000'
False positive for key 'menu.0.unitprice': GT=None, Pred='38.000'
False positive for key 'menu.5.unitprice': GT=None, Pred='20.000'
False negative for key 'sub_total.subtotal_price': GT='238.000', Pred=None
False positive for key 'menu.2.unitprice': GT=None, Pred='65.000'
False positive for key 'menu.2.itemsubtotal': GT=None, Pred='65,000'
False positive for key 'menu.1.itemsubtotal': GT=None, Pred='55,000'
False positive for key 'menu.4.unitprice': GT=None, Pred='25.000'
False positive for key 'menu.3.itemsubtotal': GT=None, Pred='35,000'
False positive for key 'menu.5.itemsubtotal': GT=None, Pred='20,000'
False positive for key 'total.menuqty_cnt': GT=None, Pred='6'
False negative for key 'total.total_etc': GT='100,000', Pred=None
False positive for key 'menu.0.itemsubtotal': GT=None, Pred='38,000'
False positive for key 'menu.3.unitprice': GT=None, Pred='35.000'
False positive for key 'menu.1.unitprice': GT=None, Pred='38.000'
False positive for key 'total.menutype_cnt': GT=None, Pred='2'
False positive for key 'menu.1.itemsubtotal': GT=None, Pred='38.000'
False positive for key 'menu.0.unitprice': GT=None, Pred='25.000'
False positive for key 'total.menuqty_cnt': GT=None, Pred='2'
False positive for key 'menu.0.itemsubtotal': GT=None, Pred='25.000'
False negative for key 'menu.0.sub.0.price': GT='0', Pred=None
False positive for key 'menu.4.cnt': GT=None, Pred='1'
False positive for key 'menu.1.price': GT='4.545', Pred='0'
False positive for key 'menu.1.nm': GT='IVINERAL WATER (bundling) 5k', Pred='L'ONGAN'
False positive for key 'menu.1.unitprice': GT=None, Pred='0'
False positive for key 'total.menutype_cnt': GT=None, Pred='5'
False negative for key 'menu.0.sub.0.nm': GT='LONGAN', Pred=None
False positive for key 'menu.4.itemsubtotal': GT=None, Pred='4,545'
False positive for key 'sub_total.price': GT=None, Pred='63.636'
False positive for key 'menu.3.nm': GT=None, Pred='MANGGO'
False positive for key 'menu.0.unitprice': GT=None, Pred='59.091'
False negative for key 'menu.0.sub.0.cnt': GT='1', Pred=None
False negative for key 'menu.0.sub.2.cnt': GT='1', Pred=None
False negative for key 'menu.0.sub.2.nm': GT='IVANGGO', Pred=None
False negative for key 'menu.0.sub.1.nm': GT='ROASTED ALMOND', Pred=None
False negative for key 'menu.0.sub.2.price': GT='0', Pred=None
False negative for key 'sub_total.etc': GT='0', Pred=None
False negative for key 'sub_total.subtotal_price': GT='63.636', Pred=None
False positive for key 'menu.3.cnt': GT=None, Pred='1'
False positive for key 'menu.2.unitprice': GT=None, Pred='0'
False positive for key 'menu.2.itemsubtotal': GT=None, Pred='0'
False negative for key 'menu.0.sub.1.price': GT='0', Pred=None
False positive for key 'menu.1.itemsubtotal': GT=None, Pred='0'
False positive for key 'menu.4.unitprice': GT=None, Pred='4.545'
False positive for key 'menu.3.itemsubtotal': GT=None, Pred='0'
False positive for key 'menu.4.nm': GT=None, Pred='MINERAL WATER (bundling) 5k'
False positive for key 'total.menuqty_cnt': GT=None, Pred='5'
False positive for key 'menu.2.nm': GT=None, Pred='ROASTED ALMOND'
False negative for key 'menu.0.sub.1.cnt': GT='1', Pred=None
False positive for key 'menu.0.itemsubtotal': GT=None, Pred='59,091'
False positive for key 'menu.3.price': GT=None, Pred='0'
False positive for key 'menu.3.unitprice': GT=None, Pred='0'
False positive for key 'menu.2.price': GT=None, Pred='0'
False positive for key 'menu.2.cnt': GT=None, Pred='1'
False positive for key 'menu.4.price': GT=None, Pred='4.545'
False positive for key 'menu.1.nm': GT='Mozarella Hot Dog', Pred='Mozzarella Hot Dog'
False positive for key 'total.menutype_cnt': GT=None, Pred='6'
False positive for key 'sub_total.price': GT=None, Pred='91.000'
False negative for key 'sub_total.subtotal_price': GT='91.000', Pred=None
False positive for key 'total.cashprice': GT=None, Pred='91.000'
False positive for key 'total.menuqty_cnt': GT=None, Pred='7'
False positive for key 'menu.2.nm': GT='Chili Pepper Croquette', Pred='Chill Pepper Croquette'
False negative for key 'total.creditcardprice': GT='91.000', Pred=None
False positive for key 'total.menutype_cnt': GT=None, Pred='1'
False positive for key 'menu.itemsubtotal': GT=None, Pred='150000'
False positive for key 'menu.unitprice': GT='156000', Pred='150000'
False positive for key 'sub_total.price': GT=None, Pred='156000'
False positive for key 'total.menuqty_cnt': GT=None, Pred='1'
False positive for key 'total.changeprice': GT='Rp. 0', Pred='0'
False positive for key 'menu.price': GT='156000', Pred='150000'
False positive for key 'menu.cnt': GT=None, Pred='14'
False negative for key 'menu.0.cnt': GT='4', Pred=None
False positive for key 'sub_total.price': GT=None, Pred='160000'
False positive for key 'total.menuqty_cnt': GT=None, Pred='14'
False negative for key 'sub_total.subtotal_price': GT='160000', Pred=None
False negative for key 'menu.1.price': GT='100000', Pred=None
False negative for key 'menu.1.nm': GT='AMBUSH CHS BUR', Pred=None
False positive for key 'total.menutype_cnt': GT=None, Pred='2'
False negative for key 'menu.1.cnt': GT='10', Pred=None
False negative for key 'menu.0.nm': GT='AMBUSH DBL CHS', Pred=None
False negative for key 'menu.0.price': GT='60000', Pred=None
False positive for key 'menu.price': GT=None, Pred='160000'
False negative for key 'menu.4.cnt': GT='4', Pred=None
False negative for key 'sub_total.subtotal_price': GT='325.600', Pred=None
False negative for key 'menu.1.price': GT='79.500', Pred=None
False negative for key 'menu.1.nm': GT='garlic pepper beef', Pred=None
False negative for key 'menu.1.cnt': GT='1', Pred=None
False negative for key 'menu.3.cnt': GT='1', Pred=None
False positive for key 'sub_total.service_price': GT='17.908', Pred='17.903'
False negative for key 'menu.0.cnt': GT='1', Pred=None
False negative for key 'menu.4.nm': GT='steamed rice', Pred=None
False negative for key 'menu.3.nm': GT='phad thai', Pred=None
False positive for key 'sub_total.price': GT=None, Pred='252.600'
False positive for key 'sub_total.tax_price': GT='34.351', Pred='54.381'
False positive for key 'total.total_price': GT='377.859', Pred='377.839'
False negative for key 'menu.2.nm': GT='red curry beef', Pred=None
False negative for key 'menu.0.nm': GT='cashew nuts chkn', Pred=None
False negative for key 'menu.0.price': GT='64.500', Pred=None
False negative for key 'menu.3.price': GT='64.500', Pred=None
False negative for key 'menu.2.price': GT='69.500', Pred=None
False negative for key 'menu.2.cnt': GT='1', Pred=None
False negative for key 'menu.4.price': GT='47.600', Pred=None
False positive for key 'total.cashprice': GT='Rp 50.000', Pred='Rp50.000'
False negative for key 'menu.0.cnt': GT='1', Pred=None
False positive for key 'sub_total.price': GT=None, Pred='Rp-38.000'
False negative for key 'menu.0.unitprice': GT='35.000', Pred=None
False negative for key 'menu.1.price': GT='Rp 3.000', Pred=None
False negative for key 'menu.1.nm': GT='ES TEH TAWAR', Pred=None
False negative for key 'menu.1.unitprice': GT='3.000', Pred=None
False positive for key 'total.total_price': GT='Rp 38.000', Pred='Rp-38.000'
False negative for key 'menu.1.cnt': GT='1', Pred=None
False negative for key 'menu.0.nm': GT='NASI GOR SFD TLR', Pred=None
False negative for key 'menu.0.price': GT='Rp 35.000', Pred=None
False positive for key 'total.changeprice': GT='Rp 12.000', Pred='Rp12.000'
False negative for key 'menu.0.cnt': GT='2', Pred=None
False positive for key 'sub_total.price': GT=None, Pred='40.000'
False negative for key 'menu.1.price': GT='20.000', Pred=None
False negative for key 'menu.1.nm': GT='[MD] SOFT STEAMED CHOCOCA', Pred=None

[Trace(trace_id=tr-1daefa2edb18521dd0f6907e4e408aa8), Trace(trace_id=tr-514f437096ed1e5b1eb2a7adb16d5666), Trace(trace_id=tr-33a6c0a30d3492c18cdc021f4315724a), Trace(trace_id=tr-d18b55b946beca7161f39841644b08e7), Trace(trace_id=tr-67280d1243178eb8ffe1290c81b121a1), Trace(trace_id=tr-b2d736bca44f4cb66c952b5b69485a91), Trace(trace_id=tr-1cf379ccf5bd54342ba2e867a2bdbd4e), Trace(trace_id=tr-4c8d446915737d32289991182914558c), Trace(trace_id=tr-1a14fbf3e809144e75bb472205f0b413), Trace(trace_id=tr-2157aa7a536969657b42a921e05f3381)]

### Count number of tokens

In [12]:
trace_df  = mlflow.search_traces(run_id=results.run_id)
print(trace_df.shape)
total_input_tokens = 0
total_output_tokens = 0
total_reasoning_tokens = 0
for i in range(len(trace_df)):
    current_usage = trace_df["response"][i]['usage']
    total_input_tokens += current_usage['prompt_tokens']
    total_output_tokens += current_usage['completion_tokens']
    total_reasoning_tokens += current_usage['completion_tokens_details']['reasoning_tokens']

print("Total input tokens:", total_input_tokens)
print("Total output tokens:", total_output_tokens)
print("Total reasoning tokens:", total_reasoning_tokens)

(100, 12)
Total input tokens: 196198
Total output tokens: 336840
Total reasoning tokens: 322944

### Publish summary

In [13]:
with mlflow.start_run(run_name=f"{MODEL_NAME}-{REASONING}-summary") as run:
    mlflow.log_params({
        "model_name": MODEL_NAME,
    })

    # Log invoice_metrics_df
    mlflow.log_artifact("artifacts/invoice_metrics.csv")

    mlflow.log_artifact("artifacts/key_metrics.csv")

    # log the token usage
    mlflow.log_metric("input_tokens", total_input_tokens)
    mlflow.log_metric("output_tokens", total_output_tokens)

🏃 View run gpt-5-nano-high-summary at: http://localhost:8080/#/experiments/417204914699444791/runs/c35dcd8dd32d4bd08cbb79fc36f4965d
🧪 View experiment at: http://localhost:8080/#/experiments/417204914699444791